home:
   path: /
   controller: App\Controller\StageAlterController::index

etablir_contrats:
   path: /etablir_contrats
   controller: App\Controller\StageAlterController::etablir_contrats

creer_contrat:
   path: /creer_contrat
   controller: App\Controller\StageAlterController::creer_contrat